// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.4
// source: verifyCode/verifyCode.proto

package verifyCode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 类型常亮
type TYPE int32

const (
	TYPE_Default TYPE = 0
	TYPE_DIGIT   TYPE = 1
	TYPE_LETTER  TYPE = 2
	TYPE_MIXED   TYPE = 3
)

// Enum value maps for TYPE.
var (
	TYPE_name = map[int32]string{
		0: "Default",
		1: "DIGIT",
		2: "LETTER",
		3: "MIXED",
	}
	TYPE_value = map[string]int32{
		"Default": 0,
		"DIGIT":   1,
		"LETTER":  2,
		"MIXED":   3,
	}
)

func (x TYPE) Enum() *TYPE {
	p := new(TYPE)
	*p = x
	return p
}

func (x TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_verifyCode_verifyCode_proto_enumTypes[0].Descriptor()
}

func (TYPE) Type() protoreflect.EnumType {
	return &file_verifyCode_verifyCode_proto_enumTypes[0]
}

func (x TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TYPE.Descriptor instead.
func (TYPE) EnumDescriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{0}
}

type CreateVerifyCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateVerifyCodeRequest) Reset() {
	*x = CreateVerifyCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifyCode_verifyCode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerifyCodeRequest) ProtoMessage() {}

func (x *CreateVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verifyCode_verifyCode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*CreateVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{0}
}

type CreateVerifyCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateVerifyCodeReply) Reset() {
	*x = CreateVerifyCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifyCode_verifyCode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerifyCodeReply) ProtoMessage() {}

func (x *CreateVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_verifyCode_verifyCode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*CreateVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{1}
}

type UpdateVerifyCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateVerifyCodeRequest) Reset() {
	*x = UpdateVerifyCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifyCode_verifyCode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVerifyCodeRequest) ProtoMessage() {}

func (x *UpdateVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verifyCode_verifyCode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{2}
}

type UpdateVerifyCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateVerifyCodeReply) Reset() {
	*x = UpdateVerifyCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifyCode_verifyCode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVerifyCodeReply) ProtoMessage() {}

func (x *UpdateVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_verifyCode_verifyCode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*UpdateVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{3}
}

type DeleteVerifyCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteVerifyCodeRequest) Reset() {
	*x = DeleteVerifyCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifyCode_verifyCode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVerifyCodeRequest) ProtoMessage() {}

func (x *DeleteVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verifyCode_verifyCode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{4}
}

type DeleteVerifyCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteVerifyCodeReply) Reset() {
	*x = DeleteVerifyCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifyCode_verifyCode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVerifyCodeReply) ProtoMessage() {}

func (x *DeleteVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_verifyCode_verifyCode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*DeleteVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{5}
}

// 定义 GetVerifyCodeRequest 消息
type GetVerifyCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//    验证码长度
	Length uint32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	// 验证码类型
	Type TYPE `protobuf:"varint,2,opt,name=type,proto3,enum=api.verifyCode.TYPE" json:"type,omitempty"`
}

func (x *GetVerifyCodeRequest) Reset() {
	*x = GetVerifyCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifyCode_verifyCode_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeRequest) ProtoMessage() {}

func (x *GetVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verifyCode_verifyCode_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{6}
}

func (x *GetVerifyCodeRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetVerifyCodeRequest) GetType() TYPE {
	if x != nil {
		return x.Type
	}
	return TYPE_Default
}

// 定义 GetVerifyCodeReply 消息
type GetVerifyCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetVerifyCodeReply) Reset() {
	*x = GetVerifyCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifyCode_verifyCode_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeReply) ProtoMessage() {}

func (x *GetVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_verifyCode_verifyCode_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{7}
}

func (x *GetVerifyCodeReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListVerifyCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVerifyCodeRequest) Reset() {
	*x = ListVerifyCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifyCode_verifyCode_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerifyCodeRequest) ProtoMessage() {}

func (x *ListVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verifyCode_verifyCode_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*ListVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{8}
}

type ListVerifyCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVerifyCodeReply) Reset() {
	*x = ListVerifyCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifyCode_verifyCode_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerifyCodeReply) ProtoMessage() {}

func (x *ListVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_verifyCode_verifyCode_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*ListVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_verifyCode_verifyCode_proto_rawDescGZIP(), []int{9}
}

var File_verifyCode_verifyCode_proto protoreflect.FileDescriptor

var file_verifyCode_verifyCode_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2f, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x19, 0x0a,
	0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x58, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x17, 0x0a,
	0x15, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2a, 0x35, 0x0a,
	0x04, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x49, 0x47, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x4c, 0x45, 0x54, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x49, 0x58,
	0x45, 0x44, 0x10, 0x03, 0x32, 0xf1, 0x03, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x62, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x62, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x62, 0x0a, 0x10, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x59, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5c, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x38, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x50, 0x01, 0x5a, 0x24, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x3b, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_verifyCode_verifyCode_proto_rawDescOnce sync.Once
	file_verifyCode_verifyCode_proto_rawDescData = file_verifyCode_verifyCode_proto_rawDesc
)

func file_verifyCode_verifyCode_proto_rawDescGZIP() []byte {
	file_verifyCode_verifyCode_proto_rawDescOnce.Do(func() {
		file_verifyCode_verifyCode_proto_rawDescData = protoimpl.X.CompressGZIP(file_verifyCode_verifyCode_proto_rawDescData)
	})
	return file_verifyCode_verifyCode_proto_rawDescData
}

var file_verifyCode_verifyCode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_verifyCode_verifyCode_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_verifyCode_verifyCode_proto_goTypes = []interface{}{
	(TYPE)(0),                       // 0: api.verifyCode.TYPE
	(*CreateVerifyCodeRequest)(nil), // 1: api.verifyCode.CreateVerifyCodeRequest
	(*CreateVerifyCodeReply)(nil),   // 2: api.verifyCode.CreateVerifyCodeReply
	(*UpdateVerifyCodeRequest)(nil), // 3: api.verifyCode.UpdateVerifyCodeRequest
	(*UpdateVerifyCodeReply)(nil),   // 4: api.verifyCode.UpdateVerifyCodeReply
	(*DeleteVerifyCodeRequest)(nil), // 5: api.verifyCode.DeleteVerifyCodeRequest
	(*DeleteVerifyCodeReply)(nil),   // 6: api.verifyCode.DeleteVerifyCodeReply
	(*GetVerifyCodeRequest)(nil),    // 7: api.verifyCode.GetVerifyCodeRequest
	(*GetVerifyCodeReply)(nil),      // 8: api.verifyCode.GetVerifyCodeReply
	(*ListVerifyCodeRequest)(nil),   // 9: api.verifyCode.ListVerifyCodeRequest
	(*ListVerifyCodeReply)(nil),     // 10: api.verifyCode.ListVerifyCodeReply
}
var file_verifyCode_verifyCode_proto_depIdxs = []int32{
	0,  // 0: api.verifyCode.GetVerifyCodeRequest.type:type_name -> api.verifyCode.TYPE
	1,  // 1: api.verifyCode.VerifyCode.CreateVerifyCode:input_type -> api.verifyCode.CreateVerifyCodeRequest
	3,  // 2: api.verifyCode.VerifyCode.UpdateVerifyCode:input_type -> api.verifyCode.UpdateVerifyCodeRequest
	5,  // 3: api.verifyCode.VerifyCode.DeleteVerifyCode:input_type -> api.verifyCode.DeleteVerifyCodeRequest
	7,  // 4: api.verifyCode.VerifyCode.GetVerifyCode:input_type -> api.verifyCode.GetVerifyCodeRequest
	9,  // 5: api.verifyCode.VerifyCode.ListVerifyCode:input_type -> api.verifyCode.ListVerifyCodeRequest
	2,  // 6: api.verifyCode.VerifyCode.CreateVerifyCode:output_type -> api.verifyCode.CreateVerifyCodeReply
	4,  // 7: api.verifyCode.VerifyCode.UpdateVerifyCode:output_type -> api.verifyCode.UpdateVerifyCodeReply
	6,  // 8: api.verifyCode.VerifyCode.DeleteVerifyCode:output_type -> api.verifyCode.DeleteVerifyCodeReply
	8,  // 9: api.verifyCode.VerifyCode.GetVerifyCode:output_type -> api.verifyCode.GetVerifyCodeReply
	10, // 10: api.verifyCode.VerifyCode.ListVerifyCode:output_type -> api.verifyCode.ListVerifyCodeReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_verifyCode_verifyCode_proto_init() }
func file_verifyCode_verifyCode_proto_init() {
	if File_verifyCode_verifyCode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_verifyCode_verifyCode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVerifyCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifyCode_verifyCode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVerifyCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifyCode_verifyCode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVerifyCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifyCode_verifyCode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVerifyCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifyCode_verifyCode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVerifyCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifyCode_verifyCode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVerifyCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifyCode_verifyCode_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVerifyCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifyCode_verifyCode_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVerifyCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifyCode_verifyCode_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVerifyCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifyCode_verifyCode_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVerifyCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_verifyCode_verifyCode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verifyCode_verifyCode_proto_goTypes,
		DependencyIndexes: file_verifyCode_verifyCode_proto_depIdxs,
		EnumInfos:         file_verifyCode_verifyCode_proto_enumTypes,
		MessageInfos:      file_verifyCode_verifyCode_proto_msgTypes,
	}.Build()
	File_verifyCode_verifyCode_proto = out.File
	file_verifyCode_verifyCode_proto_rawDesc = nil
	file_verifyCode_verifyCode_proto_goTypes = nil
	file_verifyCode_verifyCode_proto_depIdxs = nil
}
