server:
  http:
    addr: 0.0.0.0:8100
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9100
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3307)/daijia?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6391
    read_timeout: 0.2s
    write_timeout: 0.2s
Auth:
  api_key: "90feaefb-6497-4843-b0c2-f5465e53e39b"
