apiVersion: v1
kind: Service
metadata:
  name: kratos-driver-service
spec:
  selector:
    app: kratos
  ports:
#    - name: http
#      port: 8000
#      targetPort: 8000
#    - name: metrics  # Prometheus 指标端口
#      port: 9090
#      targetPort: 9090
    - name: http-api  # 暴露 8400 HTTP 接口
      port: 8400
      targetPort: 8400
    - name: grpc-api  # 暴露 9400 gRPC 接口
      port: 9400
      targetPort: 9400
  type: NodePort


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kratos-driver-grpc-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"  # 指定后端协议为 gRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - grpc-driver.devk8s.com
      secretName: wildcard-tls-secret
  rules:
    - host: grpc-driver.devk8s.com  # 自定义域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kratos-driver-service
                port:
                  number: 9400  # gRPC API 端口


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kratos-driver-http-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - http-driver.devk8s.com
      secretName: wildcard-tls-secret
  rules:
    - host: http-driver.devk8s.com  # HTTP 访问域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kratos-driver-service
                port:
                  number: 8400  # HTTP API 端口
---
