server:
  http:
    addr: 0.0.0.0:8300
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9300
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(192.168.65.128:3307)/daijia_valuation?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 192.168.65.128:6391
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  consul:
    address: 192.168.65.128:8500
    scheme: http
trace:
  enable: true
  endpoint: http://192.168.65.128:14268/api/traces
  exporter: jaeger
  token: