// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: api/mapService/mapService.proto

package mapService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDriverInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin      string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *GetDriverInfoReq) Reset() {
	*x = GetDriverInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mapService_mapService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDriverInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverInfoReq) ProtoMessage() {}

func (x *GetDriverInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapService_mapService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverInfoReq.ProtoReflect.Descriptor instead.
func (*GetDriverInfoReq) Descriptor() ([]byte, []int) {
	return file_api_mapService_mapService_proto_rawDescGZIP(), []int{0}
}

func (x *GetDriverInfoReq) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GetDriverInfoReq) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type GetDriverInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin      string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Distance    string `protobuf:"bytes,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration    string `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *GetDriverInfoResp) Reset() {
	*x = GetDriverInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mapService_mapService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDriverInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverInfoResp) ProtoMessage() {}

func (x *GetDriverInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapService_mapService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverInfoResp.ProtoReflect.Descriptor instead.
func (*GetDriverInfoResp) Descriptor() ([]byte, []int) {
	return file_api_mapService_mapService_proto_rawDescGZIP(), []int{1}
}

func (x *GetDriverInfoResp) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GetDriverInfoResp) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *GetDriverInfoResp) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *GetDriverInfoResp) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

var File_api_mapService_mapService_proto protoreflect.FileDescriptor

var file_api_mapService_mapService_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x4c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x85, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x62, 0x0a, 0x0a, 0x4d, 0x61, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x42, 0x31, 0x0a, 0x0e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x01, 0x5a,
	0x1d, 0x6d, 0x61, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x3b, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_mapService_mapService_proto_rawDescOnce sync.Once
	file_api_mapService_mapService_proto_rawDescData = file_api_mapService_mapService_proto_rawDesc
)

func file_api_mapService_mapService_proto_rawDescGZIP() []byte {
	file_api_mapService_mapService_proto_rawDescOnce.Do(func() {
		file_api_mapService_mapService_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_mapService_mapService_proto_rawDescData)
	})
	return file_api_mapService_mapService_proto_rawDescData
}

var file_api_mapService_mapService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_mapService_mapService_proto_goTypes = []interface{}{
	(*GetDriverInfoReq)(nil),  // 0: api.mapService.GetDriverInfoReq
	(*GetDriverInfoResp)(nil), // 1: api.mapService.GetDriverInfoResp
}
var file_api_mapService_mapService_proto_depIdxs = []int32{
	0, // 0: api.mapService.MapService.GetDriverInfo:input_type -> api.mapService.GetDriverInfoReq
	1, // 1: api.mapService.MapService.GetDriverInfo:output_type -> api.mapService.GetDriverInfoResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_mapService_mapService_proto_init() }
func file_api_mapService_mapService_proto_init() {
	if File_api_mapService_mapService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_mapService_mapService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDriverInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mapService_mapService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDriverInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_mapService_mapService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mapService_mapService_proto_goTypes,
		DependencyIndexes: file_api_mapService_mapService_proto_depIdxs,
		MessageInfos:      file_api_mapService_mapService_proto_msgTypes,
	}.Build()
	File_api_mapService_mapService_proto = out.File
	file_api_mapService_mapService_proto_rawDesc = nil
	file_api_mapService_mapService_proto_goTypes = nil
	file_api_mapService_mapService_proto_depIdxs = nil
}
