apiVersion: v1
kind: Service
metadata:
  name: kratos-verifycode-service
spec:
  selector:
    app: kratos
  ports:
#    - name: http
#      port: 8000
#      targetPort: 8000
#    - name: metrics  # Prometheus 指标端口
#      port: 9090
#      targetPort: 9090
    - name: http-api  # 
      port: 8600
      targetPort: 8600
    - name: grpc-api  # 
      port: 9600
      targetPort: 9600
  type: NodePort


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kratos-verifycode-grpc-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"  # 指定后端协议为 gRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - grpc-verifycode.devk8s.com
      secretName: wildcard-tls-secret
  rules:
    - host: grpc-verifycode.devk8s.com  # 自定义域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kratos-verifycode-service
                port:
                  number: 9600  # gRPC API 端口


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kratos-verifycode-http-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: http-verifycode.devk8s.com  # HTTP 访问域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kratos-verifycode-service
                port:
                  number: 8600  # HTTP API 端口
---
