server:
  http:
    addr: 0.0.0.0:8400
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9400
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(192.168.65.128:3307)/daijia_driver?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 192.168.65.128:6391
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  api_key: 90feaefb-6497-4843-b0c2-f5465e53e39b
registry:
  consul:
    address: 192.168.65.128:8500
    scheme: http
trace:
  enable: true
  endpoint: http://192.168.65.128:14268/api/traces
  exporter: jaeger
  token:
